In [1]:
import numpy as np

In [2]:
a = np.array((1,2,3))

In [4]:
a

array([1, 2, 3])

In [5]:
b = np.array((2,3,4))

In [6]:
b

array([2, 3, 4])

In [7]:
np.dstack((a,b))

array([[[1, 2],
        [2, 3],
        [3, 4]]])

In [8]:
a = np.array([[1],[2],[3]])

In [9]:
a

array([[1],
       [2],
       [3]])

In [10]:
b = np.array([[2],[3],[4]])

In [11]:
b

array([[2],
       [3],
       [4]])

In [12]:
np.dstack((a,b))

array([[[1, 2]],

       [[2, 3]],

       [[3, 4]]])